name: sport_news
description: Sport news app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  flutter_animate: ^4.0.0

  cupertino_icons: ^1.0.2

  firebase_core: ^2.13.0
  firebase_remote_config: ^4.2.1
  firebase_analytics: ^10.4.1


  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  flutter_inappwebview: ^5.7.2
  device_info_plus: ^9.0.1
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

flutter:
  generate: true
  assets:
    - assets/translations/
    - assets/images/
  uses-material-design: true
